/*-----------------------------------------------------------------------------*
 * VP_Theme.java
 * - Contains the default theme and stores custom themes
 * Authors:
 * - Team-02
 * -- William Dewald (Project Manager)
 * -- Fernando Bazan
 * -- Nathanael Carr
 * -- Erik Lopez
 * -- Raul Saavedra
 * FILE ID 5500
 *-----------------------------------------------------------------------------*/
package vaqpack.user;

public final class VP_Theme {

    /*------------------------------------------------------------------------*
     * VP_Theme()
     * - Private constructor. Cannot be instantiated
     * No Parameters.
     *------------------------------------------------------------------------*/
    private VP_Theme() {
    }

    public enum Default {
        COUNT("6"),
        
        NAME_1("Super Simple"),
        BC_CONTAINER_1(" style=\"border-collapse:collapse;margin:0;padding:0;width:3.5in;height:2in;text-align:center;vertical-align:middle;border:1px solid #000;\""),
        BC_TABLE_1(" style=\"background: rgb(255, 255, 255); border-collapse:collapse;margin:0;padding:0;width:3.5in;height:2in;text-align:center;vertical-align:middle;\""),
        BC_CELL1_1(" style =\"padding:0; margin:0;\""),
        BC_CELL2_1(""),
        BC_CELL3_1(""),
        BC_NAME_1(" style = \"font-family: 'Times New Roman', Times, serif; font-weight: bold; font-size: 12pt; display: block;\""),
        BC_PROFESSION_1(" style=\"font-family:'Times New Roman', Times, serif;font-size: 10pt; display: block;\""),
        BC_COMPANY_NAME_1(" style=\"font-family:'Times New Roman', Times, serif;font-size: 11pt; display: block;\""),
        BC_COMPANY_SLOGAN_1(" style=\"font-family:'Times New Roman', Times, serif;padding-left:20pt; font-style: italic; font-size: 10pt; display: block;\""),
        BC_ADDRESS1_1(" style=\"font-family:'Times New Roman', Times, serif;padding-top:10pt; font-size: 10pt;display: block;\""),
        BC_ADDRESS2_1(" style=\"font-family:'Times New Roman', Times, serif;font-size: 10pt; display: block;\""),
        BC_CITY_STATE_ZIP_1(" style=\"font-family:'Times New Roman', Times, serif;font-size: 10pt; display: block;\""),
        BC_PHONE_CELL_1(" style=\"font-family:'Times New Roman', Times, serif;\""),
        BC_EMAIL_1(" style=\"font-family:'Times New Roman', Times, serif;font-size: 11pt; display: block;\""),
        BC_WEB_1(" style=\"font-family:'Times New Roman', Times, serif;font-size: 9pt; display: block;\""),
        CL_BODY_1(" style=\"padding:20pt;\""),
        CL_NAME_1(" style = \"text-align:center; font-family: 'Times New Roman', Times, serif; font-weight: bold; font-size: 14pt; display: block;\""),
        CL_ADDRESS1_1(" style = \"text-align:center; font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        CL_ADDRESS2_1(" style = \"text-align:center; font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        CL_CITY_STATE_ZIP_1(" style = \"text-align:center; font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        CL_COMMUNICATION_1(" style = \"text-align:center; font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        CL_DIVIDER_1(""),
        CL_AD_1(" style = \"float:right; font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        CL_DATE_1(" style = \"font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        CL_CONTACT_NAME_1(" style = \"font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        CL_CONTACT_INFO_1(" style = \"font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        CL_SALUTATION_1(" style = \"font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        CL_CLOSING_1(" style = \"font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        CL_PARAGRAPH_1(" style = \"text-indent:1cm; padding:0 0 6px 0; margin:0; font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        CL_SIGNATURE_1(" style = \"font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        RES_BODY_1(" style=\"padding:20pt;\""),
        RES_NAME_1(" style=\"text-align:center; font-family: 'Times New Roman', Times, serif; font-weight: bold; font-size: 14pt; display: block;\""),
        RES_ADDRESS1_1(" style=\"text-align:center; font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        RES_ADDRESS2_1(" style=\"text-align:center; font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        RES_CITY_STATE_ZIP_1(" style=\"text-align:center; font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        RES_COMMUNICATION_1(" style=\"text-align:center; font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        RES_PARAGRAPHS_1(" style=\"text-indent:1cm;padding:0 0 6px 0;margin:0; font-family: 'Times New Roman', Times, serif; font-size: 12pt;\""),
        RES_TITLES_1(" style=\"text-shadow: 1px 1px 0px #F00; font-family: 'Times New Roman', Times, serif; font-weight: bold; font-size: 13pt; display: block;\""),
        RES_LISTS_1(" style=\"font-family: 'Times New Roman', Times, serif; font-size: 12pt;\""),
        RES_CONTAINERS_1(" style = \"margin-bottom: 14pt\""),
        RES_DIVIDERS_1(" style =\"margin-top: 3px\""),
        
        NAME_2("Silver"),
        BC_CONTAINER_2(" style=\"border-collapse:collapse;margin:0;padding:0;width:2in;height:3.5in;text-align:left;vertical-align:middle;border:1px solid #000;\""),
        BC_TABLE_2(" style=\"background: rgb(240, 240, 240); border-collapse:collapse;width:2in;height:3.5in;vertical-align:middle;\""),
        BC_CELL1_2(" style =\"padding:0; margin:0;\""),
        BC_CELL2_2(""),
        BC_CELL3_2(""),
        BC_NAME_2(" style=\"margin-top:8pt; margin-bottom: 2pt; padding:4pt;font-family: Arial, Helvetica, sans-serif; font-weight: bold; font-size: 11pt; display: block; color: rgb(255, 255, 255); background: rgb(60, 60, 60);\""),
        BC_PROFESSION_2(" style=\"text-align: right; padding:4pt; font-family: Arial, Helvetica, sans-serif; font-size: 9pt; display: block;\""),
        BC_COMPANY_NAME_2(" style=\"padding:4pt; font-family: Arial, Helvetica, sans-serif; font-size: 10pt; display: block;\""),
        BC_COMPANY_SLOGAN_2(" style=\"text-align: right; padding:2pt; font-family: Arial, Helvetica, sans-serif; font-size: 8pt; display: block;\""),
        BC_ADDRESS1_2(" style=\"padding:4pt;font-family: Arial, Helvetica, sans-serif; padding-top:10pt; font-size: 10pt;display: block;\""),
        BC_ADDRESS2_2(" style=\"padding:4pt;font-family: Arial, Helvetica, sans-serif; font-size: 9pt; display: block;\""),
        BC_CITY_STATE_ZIP_2(" style=\"margin-bottom: 8pt; padding:4pt;font-family: Arial, Helvetica, sans-serif; font-size: 10pt; display: block;\""),
        BC_PHONE_CELL_2(" style=\"padding:4pt;font-family: Arial, Helvetica, sans-serif; font-size: 9pt; display: block; color: black;\""),
        BC_EMAIL_2(" style=\"padding:4pt;font-family: Arial, Helvetica, sans-serif; font-size: 9pt; display: block; color: black;\""),
        BC_WEB_2(" style=\"padding:4pt; font-family: Arial, Helvetica, sans-serif; font-size: 8pt; display: block;\""),
        CL_BODY_2(" style = \"margin:0; padding: 0; padding-bottom: 20pt; background: rgb(240, 240, 240);\""),
        CL_NAME_2(" style=\"margin-bottom: 2pt; text-align:center; color: rgb(60, 60, 60); font-family: 'Arial Black', Gadget, sans-serif; font-weight: bold; font-size: 15pt; display: block; padding: 2pt;background: rgb(240, 240, 240);\""),
        CL_ADDRESS1_2(" style=\"padding: 2pt; text-align:center; font-family: Arial, Helvetica, sans-serif; font-size: 13pt; display: block;\""),
        CL_ADDRESS2_2(" style=\"padding: 2pt; text-align:center; font-family: Arial, Helvetica, sans-serif; font-size: 13pt; display: block;\""),
        CL_CITY_STATE_ZIP_2(" style=\"padding: 2pt; text-align:center; font-family: Arial, Helvetica, sans-serif; font-size: 13pt; display: block;\""),
        CL_COMMUNICATION_2(" style=\"padding: 2pt; text-align:center; font-family: Arial, Helvetica, sans-serif; font-size: 13pt; display: block;\""),
        CL_DIVIDER_2(" style = \"border: 4px solid rgb(60, 60, 60);\""),
        CL_AD_2(" style=\"float:right;padding: 2pt; padding-right:20pt; font-family: Arial, Helvetica, sans-serif; font-size: 12pt; display: block;\""),
        CL_DATE_2(" style=\"padding-left:20pt; font-family: Arial, Helvetica, sans-serif; font-size: 13pt; display: block;\""),
        CL_CONTACT_NAME_2(" style=\"padding: 2pt; padding-left:20pt; font-family: Arial, Helvetica, sans-serif; font-size: 13pt; display: block;\""),
        CL_CONTACT_INFO_2(" style=\"padding: 2pt; padding-left:20pt; font-family: Arial, Helvetica, sans-serif; font-size: 12pt; display: block;\""),
        CL_SALUTATION_2(" style=\"padding-left:20pt; font-family: Arial, Helvetica, sans-serif; font-size: 13pt; display: block;\""),
        CL_CLOSING_2(" style=\"padding-left:20pt; font-family: Arial, Helvetica, sans-serif; font-size: 13pt; display: block;\""),
        CL_PARAGRAPH_2(" style=\"padding:20pt; text-indent:1cm; margin:0; font-family: Arial, Helvetica, sans-serif; font-size: 13pt; display: block;\""),
        CL_SIGNATURE_2(" style=\"padding-left:20pt; font-family: Arial, Helvetica, sans-serif; font-size: 13pt; display: block;\""),
        RES_BODY_2(" style = \"margin:0; padding: 0; padding-bottom: 20pt; background: rgb(240, 240, 240);\""),
        RES_NAME_2(" style=\"margin-bottom: 2pt; text-align:center; color: rgb(60, 60, 60); font-family: 'Arial Black', Gadget, sans-serif; font-weight: bold; font-size: 15pt; display: block; padding: 2pt;background: rgb(240, 240, 240);\""),
        RES_ADDRESS1_2(" style=\"padding: 2pt; text-align:center; font-family: Arial, Helvetica, sans-serif; font-size: 13pt; display: block;\""),
        RES_ADDRESS2_2(" style=\"padding: 2pt; text-align:center; font-family: Arial, Helvetica, sans-serif; font-size: 13pt; display: block;\""),
        RES_CITY_STATE_ZIP_2(" style=\"padding: 2pt; text-align:center; font-family: Arial, Helvetica, sans-serif; font-size: 13pt; display: block;\""),
        RES_COMMUNICATION_2(" style=\"padding: 2pt; text-align:center; font-family: Arial, Helvetica, sans-serif; font-size: 13pt; display: block;\""),
        RES_PARAGRAPHS_2(" style=\"padding:20pt; text-indent:1cm; margin:0; font-family: 'Arial', Helvetica, sans-serif; font-size: 12pt;\""),
        RES_TITLES_2(" style=\"font-family: 'Arial', Helvetica, sans-serif; font-weight: bold; font-size: 13pt; display: block; padding: 2pt; padding-left: 8pt; background: rgb(204, 204, 204);\""),
        RES_LISTS_2(" style=\"padding:0 0 6px 0;margin:0; font-family: Arial, Helvetica, sans-serif; font-size: 12pt;\""),
        RES_CONTAINERS_2(" style=\"padding-left:20pt; margin-bottom: 14pt;\""),
        RES_DIVIDERS_2(" style =\"margin: 0; padding: 0; height: 0; border: 0;\""),
        
        NAME_3("Boxy Brown"),
        BC_CONTAINER_3(" style=\"margin:0;padding:0;width:3.5in;height:2in;text-align:center;vertical-align:middle;border:1px solid #000;\""),
        BC_TABLE_3(" style=\"background-color: rgb(249, 242, 236);width:3.5in;height:2in;text-align:center;vertical-align:middle;\""),
        BC_CELL1_3(" style = \"padding:2px; border: 1px solid rgb(171, 105, 48);\""),
        BC_CELL2_3(""),
        BC_CELL3_3(""),
        BC_NAME_3(" style=\"padding: 2px; color: rgb(51, 34, 19); font-family: 'Georgia', Times, serif; font-weight: bold; font-size: 10pt; font-variant: small-caps;display: block;\""),
        BC_PROFESSION_3(" style=\"padding: 2px; color: rgb(51, 34, 19); font-family:'Georgia', Times, serif;font-size: 7pt; font-variant: small-caps; display: block;\""),
        BC_COMPANY_NAME_3(" style=\"padding: 2px; color: rgb(51, 34, 19); font-family:'Georgia', Times, serif;font-size: 9pt; display: block;\""),
        BC_COMPANY_SLOGAN_3(" style=\"padding: 2px; color: rgb(51, 34, 19); font-family:'Georgia', Times, serif;padding-left:20px; font-style: italic; font-size: 7pt; display: block;\""),
        BC_ADDRESS1_3(" style=\"padding: 2px; color: rgb(51, 34, 19); font-family:'Georgia', Times, serif; font-size: 9pt;display: block;\""),
        BC_ADDRESS2_3(" style=\"padding: 2px; color: rgb(51, 34, 19); font-family:'Georgia', Times, serif;font-size: 7pt; display: block;\""),
        BC_CITY_STATE_ZIP_3(" style=\"padding: 2px; color: rgb(51, 34, 19); font-family:'Georgia', Times, serif;font-size: 7pt; display: block;\""),
        BC_PHONE_CELL_3(" style=\"padding: 2px; color: rgb(51, 34, 19); font-family:'Georgia', Times, serif;font-size: 9pt;\""),
        BC_EMAIL_3(" style=\"padding: 2px; color: rgb(51, 34, 19); font-family:'Georgia', Times, serif;font-size: 7pt; display: block;\""),
        BC_WEB_3(" style=\"padding: 2px; color: rgb(51, 34, 19); font-family:'Georgia', Times, serif;font-size: 7pt; display: block;\""),
        CL_BODY_3(" style=\"color: rgb(51, 34, 19); margin:0; padding: 0; padding-bottom: 20pt; background-color: rgb(249, 242, 236);\""),
        CL_NAME_3(" style=\"background-color: rgb(255, 248, 242);margin-top: 40px; border: solid rgb(171, 105, 48); border-width: 7px 0 0 0; padding: 20px; text-align:center; font-family: 'Georgia', Times, serif; font-weight: bold; font-variant: small-caps; letter-spacing: 2px; font-size: 16pt; display: block;\""),
        CL_ADDRESS1_3(" style=\"background-color: rgb(255, 248, 242);text-align:center; font-family: 'Georgia', Times, serif; font-size: 12pt; display: block;\""),
        CL_ADDRESS2_3(" style=\"background-color: rgb(255, 248, 242);text-align:center; font-family: 'Georgia', Times, serif; font-size: 12pt; display: block;\""),
        CL_CITY_STATE_ZIP_3(" style=\"background-color: rgb(255, 248, 242);text-align:center; font-family: 'Georgia', Times, serif; font-size: 12pt; display: block;\""),
        CL_COMMUNICATION_3(" style=\"padding: 8px 0 20px 0; background-color: rgb(255, 248, 242); border: solid rgb(171, 105, 48); border-width: 0 0 4px 0;text-align:center; font-family: 'Georgia', Times, serif; font-size: 12pt; display: block;\""),
        CL_DIVIDER_3(" style =\"margin: 0; padding: 0; height: 0; border: 0;\""),
        CL_AD_3(" style = \"background-color: rgb(255, 248, 242); margin-right: 20px; vertical-align: top; padding:20px; border: 1px solid rgb(171, 105, 48); float:right; font-family: 'Georgia', Times, serif; font-size: 12pt; display: block;\""),
        CL_DATE_3(" style=\"padding-left:20px; font-family: 'Georgia', Times, serif; font-size: 12pt; display: block;\""),
        CL_CONTACT_NAME_3(" style= \"padding-left:20px; font-family: 'Georgia', Times, serif; font-size: 12pt; display: block;\""),
        CL_CONTACT_INFO_3(" style=\"padding-left:20px; font-family: 'Georgia', Times, serif; font-size: 10pt; display: block;\""),
        CL_SALUTATION_3(" style=\"padding-left:20px; font-family: 'Georgia', Times, serif; font-size: 12pt; display: block;\""),
        CL_CLOSING_3(" style=\"padding-left:20px; font-family: 'Georgia', Times, serif; font-size: 12pt; display: block;\""),
        CL_PARAGRAPH_3(" style=\"padding: 0 20px 0 20px; text-indent:1cm; margin:0; font-family: 'Georgia', Times, serif; font-size: 12pt; display: block;\""),
        CL_SIGNATURE_3(" style=\"margin-bottom: 40px; border: solid rgb(171, 105, 48); border-width: 0 0 12px 0; padding: 0 20px 20px 20px; font-family: 'Georgia', Times, serif; font-size: 12pt; display: block;\""),
        RES_BODY_3(" style=\"color: rgb(51, 34, 19); margin:0; padding: 0; padding-bottom: 20pt; background-color: rgb(249, 242, 236);\""),
        RES_NAME_3(" style=\"background-color: rgb(255, 248, 242);margin-top: 40px; border: solid rgb(171, 105, 48); border-width: 7px 0 0 0; padding: 20px; text-align:center; font-family: 'Georgia', Times, serif; font-weight: bold; font-variant: small-caps; letter-spacing: 2px; font-size: 16pt; display: block;\""),
        RES_ADDRESS1_3(" style=\"background-color: rgb(255, 248, 242);text-align:center; font-family: 'Georgia', Times, serif; font-size: 12pt; display: block;\""),
        RES_ADDRESS2_3(" style=\"background-color: rgb(255, 248, 242);text-align:center; font-family: 'Georgia', Times, serif; font-size: 12pt; display: block;\""),
        RES_CITY_STATE_ZIP_3(" style=\"background-color: rgb(255, 248, 242);text-align:center; font-family: 'Georgia', Times, serif; font-size: 12pt; display: block;\""),
        RES_COMMUNICATION_3(" style=\"padding: 8px 0 20px 0; background-color: rgb(255, 248, 242); border: solid rgb(171, 105, 48); border-width: 0 0 4px 0;text-align:center; font-family: 'Georgia', Times, serif; font-size: 12pt; display: block;\""),
        RES_PARAGRAPHS_3(" style=\"padding-left:20px; text-indent:1cm; margin:0; font-family: 'Georgia', Times, serif; font-size: 12pt; display: block;\""),
        RES_TITLES_3(" style=\"margin: 14pt; padding-left:20px; border: solid rgb(171, 105, 48); border-width: 0 0 7px 0; font-family: 'Georgia', Times, serif; font-weight: bold; font-size: 13pt; display: block;\""),
        RES_LISTS_3(" style=\"padding-left:20px; font-family: 'Georgia', Times, serif; font-size: 12pt;\""),
        RES_CONTAINERS_3(" style = \"padding-left:20px;  margin: 14pt; border: 1px solid rgb(171, 105, 48);\""),
        RES_DIVIDERS_3(" style =\"margin: 0; padding: 0; height: 0; border: 0;\""),
        
        NAME_4("Wild Cherry"),
        BC_CONTAINER_4(" style=\"background-color: rgb(255, 0, 0); border-collapse:collapse;margin:0;padding:2px;;width:3.5in;height:2in;vertical-align:middle;border:1px solid #000;\""),
        BC_TABLE_4(" style=\"background-color: rgb(80, 0, 0); border: 4px solid rgb(140, 0, 0); border-collapse:collapse;margin:0;padding:0;width:3.5in;height:2in;vertical-align:middle;\""),
        BC_CELL1_4(" style = \"text-align:left; padding-left: 6px; padding-right: 6px;\""),
        BC_CELL2_4(""),
        BC_CELL3_4(""),
        BC_NAME_4(" style=\"text-align:center; font-family: 'Times New Roman', Times, serif;color:white;font-weight: bold; font-size: 12pt; display: block;\""),
        BC_PROFESSION_4(" style=\"font-family:'Times New Roman', Times, serif;color:white;padding-left:80px;font-size: 9pt; display: block;\""),
        BC_COMPANY_NAME_4(" style=\"font-family:'Times New Roman', Times, serif;color:white;padding-left:120px;font-size: 10pt; display: block;\""),
        BC_COMPANY_SLOGAN_4(" style=\"text-align: right; font-family:'Times New Roman', Times, serif; color:white;padding-right:40px; font-style: italic; font-size: 8pt; display: block;\""),
        BC_ADDRESS1_4(" style=\"font-family:'Times New Roman', Times, serif;color:white;padding-left:5;padding-top:10pt; font-size: 10pt;display: block;\""),
        BC_ADDRESS2_4(" style=\"font-family:'Times New Roman', Times, serif;color:white;padding-left:5;font-size: 9pt; display: block;\""),
        BC_CITY_STATE_ZIP_4(" style=\"font-family:'Times New Roman', Times, serif;color:white;padding-left:5;font-size: 9pt; display: block;\""),
        BC_PHONE_CELL_4(" style=\"font-family:'Times New Roman', Times, serif;color:white;padding-left:5;font-size: 10pt;\""),
        BC_EMAIL_4(" style=\"font-family:'Times New Roman', Times, serif;color:white;padding-right:5;text-align:right;font-size: 10pt; display: block;\""),
        BC_WEB_4(" style=\"font-family:'Times New Roman', Times, serif;color:white;padding-right:5;text-align:right;font-size: 8pt; display: block;\""),
        CL_BODY_4(" style=\"color: rgb(80, 0, 0);padding:20px;background-color: rgb(255, 245, 245);border: 4px solid rgb(140, 0, 0);margin: 0\""),
        CL_NAME_4(" style=\"color: rgb(255, 245, 245);border: 4px solid rgb(140, 0, 0); border-bottom: 0; background-color: rgb(80, 0, 0); text-align:center; font-family: 'Helvetica', Times, serif; font-weight: bold; font-size: 14pt; display: block;\""),
        CL_ADDRESS1_4(" style=\"color: rgb(255, 245, 245);border: 4px solid rgb(140, 0, 0); border-bottom: 0; border-top: 0; background-color: rgb(80, 0, 0); text-align:center; font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        CL_ADDRESS2_4(" style=\"color: rgb(255, 245, 245);border: 4px solid rgb(140, 0, 0); border-bottom: 0; border-top: 0; background-color: rgb(80, 0, 0); text-align:center; font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        CL_CITY_STATE_ZIP_4(" style=\"color: rgb(255, 245, 245);border: 4px solid rgb(140, 0, 0); border-bottom: 0; border-top: 0; background-color: rgb(80, 0, 0); text-align:center; font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        CL_COMMUNICATION_4(" style=\"color: rgb(255, 245, 245);border: 4px solid rgb(140, 0, 0); border-top: 0; background-color: rgb(80, 0, 0); text-align:center; font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        CL_DIVIDER_4(" style = \"border: 2px solid rgb(140, 0, 0);\""),
        CL_AD_4(" style=\"float:right; font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        CL_DATE_4(" style=\"font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        CL_CONTACT_NAME_4(" style=\"font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        CL_CONTACT_INFO_4(" style=\"font-family: 'Times New Roman', Times, serif; font-size: 11pt; display: block;\""),
        CL_SALUTATION_4(" style=\"padding-top:10px; border-top: 4px solid rgb(140, 0, 0); font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        CL_CLOSING_4(" style=\"font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        CL_PARAGRAPH_4(" style=\"text-indent:1cm; padding:0 0 6px 0; margin:0; font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        CL_SIGNATURE_4(" style=\"font-family: 'Vladimir Script', Times, serif;text-indent:1cm; font-size: 24pt; display: block;\""),
        RES_BODY_4(" style=\"color: rgb(80, 0, 0);padding:20px;background-color: rgb(255, 245, 245);border: 4px solid rgb(140, 0, 0);margin: 0\""),
        RES_NAME_4(" style=\"color: rgb(255, 245, 245);border: 4px solid rgb(140, 0, 0); border-bottom: 0; background-color: rgb(80, 0, 0); text-align:center; font-family: 'Helvetica', Times, serif; font-weight: bold; font-size: 14pt; display: block;\""),
        RES_ADDRESS1_4(" style=\"color: rgb(255, 245, 245);border: 4px solid rgb(140, 0, 0); border-bottom: 0; border-top: 0; background-color: rgb(80, 0, 0); text-align:center; font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        RES_ADDRESS2_4(" style=\"color: rgb(255, 245, 245);border: 4px solid rgb(140, 0, 0); border-bottom: 0; border-top: 0; background-color: rgb(80, 0, 0); text-align:center; font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        RES_CITY_STATE_ZIP_4(" style=\"color: rgb(255, 245, 245);border: 4px solid rgb(140, 0, 0); border-bottom: 0; border-top: 0; background-color: rgb(80, 0, 0); text-align:center; font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        RES_COMMUNICATION_4(" style=\"color: rgb(255, 245, 245);border: 4px solid rgb(140, 0, 0); border-top: 0; background-color: rgb(80, 0, 0); text-align:center; font-family: 'Times New Roman', Times, serif; font-size: 12pt; display: block;\""),
        RES_PARAGRAPHS_4(" style=\"text-indent:1cm;padding:0 0 6px 0;margin:0; font-family: 'Times New Roman', Times, serif; font-size: 12pt;\""),
        RES_TITLES_4(" style=\"text-align:center; border: 1px solid rgb(140, 0, 0); font-family: 'Helvetica', Times, serif;background-color:#ff9999; font-weight: bold; font-size: 13pt; display: block;\""),
        RES_LISTS_4(" style=\"font-family: 'Times New Roman', Times, serif; font-size: 12pt;\""),
        RES_CONTAINERS_4(" style = \"padding-left:20px;  margin-bottom: 14pt; border: 1px solid rgb(255, 250, 250);\""),
        RES_DIVIDERS_4(" style = \"border: 2px solid rgb(140, 0, 0);\""),
        
        NAME_5("Vaquero"),
        BC_CONTAINER_5(" style=\"border-collapse:collapse;margin:0;padding:0;width:3.5in;height:2in;text-align:center;vertical-align:middle; background: rgb(0, 38, 73);\""),
        BC_TABLE_5(" style=\"font-family: 'Helvetica', Arial, sans-serif; color: rgb(255, 255, 255);\""),
        BC_CELL1_5(" style=\"padding:8px; vertical-align: top; line-height: 1.25em; font-weight: bold; width: 40%;\""),
        BC_CELL2_5(" style=\"white-space:nowrap; padding:8px; vertical-align: top; line-height: 1.5em; font-size: 10pt; width: 60%; text-align: right;\""),
        BC_CELL3_5(" colspan=\"2\" style=\"font-size: 10pt; width:3.5in; padding: 4px 8px; color: rgb(255, 255, 255); line-height:1.25em; background:rgb(0, 115, 61); border-top: solid 1px rgb(255, 255, 255);\""),
        BC_NAME_5(" style=\"margin-bottom: 8px; font-size: 13pt; line-height: 1.25em; color: rgb(249, 86, 2);\""),
        BC_PROFESSION_5(" style=\"font-size: 10pt; font-weight: normal;\""),
        BC_COMPANY_NAME_5(" style=\"font-size: 10pt; font-weight: normal;\""),
        BC_COMPANY_SLOGAN_5(" style=\"font-size: 9pt; font-weight: normal;\""),
        BC_ADDRESS1_5(""),
        BC_ADDRESS2_5(""),
        BC_CITY_STATE_ZIP_5(""),
        BC_PHONE_CELL_5(""),
        BC_EMAIL_5(""),
        BC_WEB_5(""),
        CL_BODY_5(" style=\"padding:20px; line-height: 1.25em; font-family: 'Helvetica', Arial, sans-serif; font-size: 12pt;\""),
        CL_NAME_5(" style=\"background: rgb(0, 38, 73);line-height: 1.5em; text-align:center; font-weight: bold; font-size: 14pt; display: block; color: #fb8b00;\""),
        CL_ADDRESS1_5(" style=\"background: rgb(0, 38, 73);color: rgb(255, 255, 255); line-height: 1.5em; text-align:center; display: block;\""),
        CL_ADDRESS2_5(" style=\"background: rgb(0, 38, 73);color: rgb(255, 255, 255); line-height: 1.5em; text-align:center; display: block;\""),
        CL_CITY_STATE_ZIP_5(" style=\"background: rgb(0, 38, 73);color: rgb(255, 255, 255); line-height: 1.5em; text-align:center; display: block;\""),
        CL_COMMUNICATION_5(" style=\"background: rgb(0, 38, 73);line-height: 1.5em;text-align:center; display: block; color: #fb8b00; font-size: 10pt;\""),
        CL_DIVIDER_5(" style=\"margin-top: 2px; background:rgb(0, 115, 61); height: 6px;\""),
        CL_AD_5(" style=\"float:right; display: block; font-size: 10pt;\""),
        CL_DATE_5(" style=\" display: block; font-size:10pt;font-weight:bold;\""),
        CL_CONTACT_NAME_5(" style=\" display: block; font-size: 10pt;\""),
        CL_CONTACT_INFO_5(" style=\" display: block; font-size: 10pt;\""),
        CL_SALUTATION_5(" style=\" display: block;\""),
        CL_CLOSING_5(" style=\" display: block;font-style:italic;\""),
        CL_PARAGRAPH_5(" style=\"text-indent:1cm; padding:0 0 6px 0; margin:0; display: block;\""),
        CL_SIGNATURE_5(" style=\" display: block; font-weight:bold;\""),
        RES_BODY_5(" style=\"padding:20px; line-height: 1.25em; font-family: 'Helvetica', Arial, sans-serif; font-size: 12pt;\""),
        RES_NAME_5(" style=\"background: rgb(0, 38, 73);line-height: 1.5em; text-align:center; font-weight: bold; font-size: 14pt; display: block; color: #fb8b00;\""),
        RES_ADDRESS1_5(" style=\"background: rgb(0, 38, 73);color: rgb(255, 255, 255); line-height: 1.5em; text-align:center; display: block;\""),
        RES_ADDRESS2_5(" style=\"background: rgb(0, 38, 73);color: rgb(255, 255, 255); line-height: 1.5em; text-align:center; display: block;\""),
        RES_CITY_STATE_ZIP_5(" style=\"background: rgb(0, 38, 73);color: rgb(255, 255, 255); line-height: 1.5em; text-align:center; display: block;\""),
        RES_COMMUNICATION_5(" style=\"background: rgb(0, 38, 73);line-height: 1.5em;text-align:center; display: block; color: #fb8b00; font-size: 10pt;\""),
        RES_PARAGRAPHS_5(" style=\"text-indent:1cm; padding:0 0 6px 0; margin:0; display: block;\""),
        RES_TITLES_5(" style=\" font-weight: bold; font-size: 13pt; background-color: #0b203a; color: #fb8b00; display: block; padding: 8px 8px 2px;\""),
        RES_LISTS_5(""),
        RES_CONTAINERS_5(" style=\"margin-bottom: 14pt\""),
        RES_DIVIDERS_5(" style=\"margin-top: 2px; background-color: #007030; height: 6px;\""),
        
        NAME_6("Icy Blue"),
        BC_CONTAINER_6(" style=\"border-collapse:collapse;margin:0;padding:0;width:3.5in;height:2in;text-align:center;vertical-align:middle; background: rgb(0, 38, 64);\""),
        BC_TABLE_6(" style=\"width:3.5in;height:2in; border: 1px solid rgb(0, 0, 100); font-family: 'Helvetica', Arial, sans-serif; color: rgb(235, 235, 255);\""),
        BC_CELL1_6(" style=\"padding:8px; vertical-align: top; line-height: 1.25em; font-weight: bold; width: 40%;\""),
        BC_CELL2_6(" style=\"white-space:nowrap; padding:8px; vertical-align: top; line-height: 1.5em; font-size: 10pt; width: 60%; text-align: right;\""),
        BC_CELL3_6(" colspan=\"2\" style=\"border-bottom: 1px solid rgb(0, 0, 100); background-color: rgb(77, 107, 117);font-size: 10pt; width:3.5in; padding: 4px 8px; color: rgb(235, 235, 255); line-height:1.25em; border-top: 1px solid rgb(235, 235, 255);\""),
        BC_NAME_6(" style=\"margin-bottom: 8px; font-size: 13pt; line-height: 1.25em; color: rgb(174, 209, 232);\""),
        BC_PROFESSION_6(" style=\"font-size: 10pt; font-weight: normal;\""),
        BC_COMPANY_NAME_6(" style=\"font-size: 10pt; font-weight: normal;\""),
        BC_COMPANY_SLOGAN_6(" style=\"font-size: 9pt; font-weight: normal;\""),
        BC_ADDRESS1_6(" style=\"font-size: 9pt; font-weight: normal;\""),
        BC_ADDRESS2_6(" style=\"font-size: 9pt; font-weight: normal;\""),
        BC_CITY_STATE_ZIP_6(" style=\"font-size: 9pt; font-weight: normal;\""),
        BC_PHONE_CELL_6(" style=\"font-size: 10pt; font-weight: normal;\""),
        BC_EMAIL_6(" style=\"font-size: 10pt; font-weight: normal;\""),
        BC_WEB_6(" style=\"font-size: 10pt; font-weight: normal;\""),
        CL_BODY_6(" style=\"color: rgb(0, 0, 30); background: rgb(240, 240, 255);padding:20px; line-height: 1.25em; font-family: 'Helvetica', Arial, sans-serif; font-size: 12pt;\""),
        CL_NAME_6(" style=\"border: 3px solid rgb(174, 209, 232); border-bottom: 0; background: rgb(0, 38, 64);line-height: 1.5em; text-align:center; font-weight: bold; font-size: 14pt; display: block; color: rgb(174, 209, 232);\""),
        CL_ADDRESS1_6(" style=\"border: 3px solid rgb(174, 209, 232); border-bottom: 0; border-top: 0;background: rgb(0, 38, 64);color: rgb(235, 235, 255); line-height: 1.5em; text-align:center; display: block;\""),
        CL_ADDRESS2_6(" style=\"border: 3px solid rgb(174, 209, 232); border-bottom: 0; border-top: 0;background: rgb(0, 38, 64);color: rgb(235, 235, 255); line-height: 1.5em; text-align:center; display: block;\""),
        CL_CITY_STATE_ZIP_6(" style=\"border: 3px solid rgb(174, 209, 232); border-bottom: 0; border-top: 0;background: rgb(0, 38, 64);color: rgb(235, 235, 255); line-height: 1.5em; text-align:center; display: block;\""),
        CL_COMMUNICATION_6(" style=\"border: 3px solid rgb(174, 209, 232); border-top: 0;background: rgb(0, 38, 64);line-height: 1.5em;text-align:center; display: block; color: rgb(174, 209, 232); font-size: 10pt;\""),
        CL_DIVIDER_6(" style=\"border-bottom: 1px solid rgb(0, 0, 100); margin-top: 2px; background-color: rgb(77, 107, 117); height: 6px;\""),
        CL_AD_6(" style=\"float:right; display: block; font-size: 10pt;\""),
        CL_DATE_6(" style=\" display: block; font-size:10pt;font-weight:bold;\""),
        CL_CONTACT_NAME_6(" style=\" display: block; font-size: 10pt;\""),
        CL_CONTACT_INFO_6(" style=\" display: block; font-size: 10pt;\""),
        CL_SALUTATION_6(" style=\" display: block;\""),
        CL_CLOSING_6(" style=\" display: block;font-style:italic;\""),
        CL_PARAGRAPH_6(" style=\"text-indent:1cm; padding:0 0 6px 0; margin:0; display: block;\""),
        CL_SIGNATURE_6(" style=\" display: block; font-weight:bold;\""),
        RES_BODY_6(" style=\"color: rgb(0, 0, 30); background: rgb(240, 240, 255);padding:20px; line-height: 1.25em; font-family: 'Helvetica', Arial, sans-serif; font-size: 12pt;\""),
        RES_NAME_6(" style=\"border: 3px solid rgb(174, 209, 232); border-bottom: 0; background: rgb(0, 38, 64);line-height: 1.5em; text-align:center; font-weight: bold; font-size: 14pt; display: block; color: rgb(174, 209, 232);\""),
        RES_ADDRESS1_6(" style=\"border: 3px solid rgb(174, 209, 232); border-bottom: 0; border-top: 0;background: rgb(0, 38, 64);color: rgb(235, 235, 255); line-height: 1.5em; text-align:center; display: block;\""),
        RES_ADDRESS2_6(" style=\"border: 3px solid rgb(174, 209, 232); border-bottom: 0; border-top: 0;background: rgb(0, 38, 64);color: rgb(235, 235, 255); line-height: 1.5em; text-align:center; display: block;\""),
        RES_CITY_STATE_ZIP_6(" style=\"border: 3px solid rgb(174, 209, 232); border-bottom: 0; border-top: 0;background: rgb(0, 38, 64);color: rgb(235, 235, 255); line-height: 1.5em; text-align:center; display: block;\""),
        RES_COMMUNICATION_6(" style=\"border: 3px solid rgb(174, 209, 232); border-top: 0;background: rgb(0, 38, 64);line-height: 1.5em;text-align:center; display: block; color: rgb(174, 209, 232); font-size: 10pt;\""),
        RES_PARAGRAPHS_6(" style=\"text-indent:1cm; padding:0 0 6px 0; margin:0; display: block;\""),
        RES_TITLES_6(" style=\"border: 3px solid rgb(174, 209, 232);text-align:center; font-weight: bold; font-size: 13pt; background: rgb(0, 38, 64); color: rgb(174, 209, 232); display: block; padding: 8px 8px 2px;\""),
        RES_LISTS_6(""),
        RES_CONTAINERS_6(" style=\"margin-bottom: 14pt\""),
        RES_DIVIDERS_6(" style=\"border-bottom: 1px solid rgb(0, 0, 100); margin-top: 2px; background-color: rgb(77, 107, 117); height: 6px;\"");

        private final String value;
        
        private Default(String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return value;
        }
    }
    



    /*##########################################################################
     * SUBCLASSES
     *########################################################################*/
    /*##########################################################################
     * SETTERS AND GETTERS
     *########################################################################*/
}
